import styles from "@/styles/Home.module.css";
import Head from "next/head";
import Link from "next/link";
import { Container, Navbar , NavLink} from "react-bootstrap";
import "bootstrap/dist/css/bootstrap.min.css";
import { useSession, signOut, getSession } from "next-auth/react";

export default function Home() {
  const { data: session, status } = useSession();
  if (session) {
    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.background2}>
        <Navbar bg="dark" variant="dark" collapseOnSelect expand="sm" >
        <Navbar.Toggle aria-controls="navbarScroll" data-bs-target="#navbarScroll"/>
        <Container>
          <Navbar.Brand href="/">
            <h2 className={styles.navBrand}>Cdata</h2>
          </Navbar.Brand>
          <Navbar.Collapse>
            <NavLink eventKey="1">
            <Link href="/" className={styles.navlink}>
            Home
          </Link>
            </NavLink>
            <NavLink eventKey="2">
          <Link href="/students" className={styles.navlink}>
            students
          </Link>
          </NavLink>
          <NavLink eventKey="3">
          <Link href="/teachers" className={styles.navlink}>
            teachers
          </Link>
          </NavLink>
          </Navbar.Collapse>
        
          <button className="btn btn-danger" onClick={() => signOut()} >SignOut</button>
        </Container>
      </Navbar>
          <div>
            <h1 className={styles.title}>Welcome to cdata</h1>
            <h5 className={styles.title}>Details Of Students and Teachers are available here</h5>
          
          </div>
        </main>
      </>
    );
  } else {
    return (
      <div>
        <p>You are not signed in</p>
      </div>
    );
  }
}
export const getServerSideProps = async (context) => {
  const session = await getSession(context);
  if(!session){
      return {
          redirect:{
              destination:'/login'
          }
      }
  }
  return{
      props:{session},
  }
  }