import styles from "@/styles/Home.module.css";
import Head from "next/head";
import Link from "next/link";
import { Container, Navbar } from "react-bootstrap";
import "bootstrap/dist/css/bootstrap.min.css";
import { useSession, signOut, getSession } from "next-auth/react";
import Announcements from "@/pages/components/announcements";

export default function Home() {
  const { data: session, status } = useSession();
  if (status === "authenticated") {
    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.background2}>
          <Navbar bg="dark" variant="dark">
            <Container>
              <Navbar.Brand href="/">
                <h2 className={styles.navBrand}>Cdata</h2>
              </Navbar.Brand>
              <Link href="/" className={styles.navlink}>
                Home
              </Link>
              <Link href="/students" className={styles.navlink}>
                students
              </Link>
              <Link href="/teachers" className={styles.navlink}>
                teachers
              </Link>
              <button onClick={() => signOut()}>SignOut</button>
            </Container>
          </Navbar>
          <div>
            <h1 className={styles.title}>Announcements</h1>
          <Announcements/>
          </div>
        </main>
      </>
    );
  } else {
    return (
      <div>
        <p>You are not signed in</p>
      </div>
    );
  }
}
export const getServerSideProps = async (context) => {
  const session = await getSession(context);
  if(!session){
      return {
          redirect:{
              destination:'/login'
          }
      }
  }
  return{
      props:{session},
  }
  }